version: "3.8"

services:

  web:
    depends_on:
      - api
    build: ./frontend
    ports:
      - 8000:8000
    environment:
      REACT_APP_API_URL: http://api:8000/api/v1

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  api:
    depends_on:
      - db
    build: ./backend
    ports:
      - 8100:8000  
    environment:
      DB_URL: mongodb://localhost:27017/minicart

    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /app
          action: sync

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mern:/data/db

volumes:
  mern:
